repos:
  - repo: local
    hooks:
      - id: isort
        name: isort - sorting python imports
        entry: poetry run isort .
        args: ["--profile", "black"]
        stages: [commit]
        language: python
        pass_filenames: false
        language: system

      - id: black - python code formatting
        name: black
        entry: poetry run black .
        stages: [commit]
        language: system
        pass_filenames: false